### ISSUE TITLE
No quick view

### ISSUE THREAD

**Issue by MrPoetry** [mangecoeur/Citer#20]
I suspect this is my user error, but Citer appears not to be responding to me.

I copied your sample settings file, pasted it into Citer's User settings, and supplied the absolute path to my Bibtex file ("/Volumes/My Data Disk/My Research Folder/CatchAll.bib").

When I do cmd-shift-p and select Citer: Insert Title or Show All, nothing happens. When I select Citer: Search, a search box comes up at the bottom, but when I type an author's last name and hit Enter, nothing happens.

Like I said at the top, I'm not even sure I fully understand how to use Citer properly, and I'd welcome any links to instructions-for-noobs.

**Comment by perturbation** [comment]
I went through the same process and am having the same issues. But I'm not sure if it's user error? This is on ST3 3083.

**Comment by perturbation** [comment]
Setting the path to my bibtex file then quitting and reopening Sublime Text seems to have resolved the problem. Maybe there's some processing Citer does only when ST is opening?

**Comment by MrPoetry** [comment]
That did it for me, too. Problem solved. Thanks, Perturbation!
