### ISSUE TITLE
Show All displays duplicate entries

### ISSUE THREAD

**Issue by rjww** [mangecoeur/Citer#21]
I've just started breaking my bibliography across multiple `.bib` files and including them as an array under `bibtex_file_path`. But this seems to be causing the Show All command to display duplicates of each entry, apparently equal to the number of files in the array. In other words, each book, article, case, etc will be listed two, three or four times, depending on whether I've included two, three or four `.bib` files in Citer.

**Comment by mangecoeur** [comment]
Thanks for spotting this, will take a look when i have time

**Comment by mangecoeur** [comment]
Was fixed a while ago.
