### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by mendelkranz** [mangecoeur/Citer#22]
I see this issue here: [#12](https://github.com/mangecoeur/Citer/issues/12), however even when I press tab I still don't get an autocomplete. Here is the preferences I have saved, is there something I'm doing wrong?

    {
      //REQUIRED:
  
      "bibtex_file_path":"/Users/Mendel/github/papers/main.bib",
  
      //OPTIONAL:
  
      //By default Citer Search looks for your keyword in the 
      //author, title, year, and Citekey (id) feilds
      "search_fields": ["author", "title", "year", "id"] ,
      //Default format is @Citekey
      "citation_format": "[@%s]",
      //list of scopes. Could be top level "text" or "source", or limit to
      // e.g "text.html.markdown"
      "completions_scopes": ["text.markdown.md.html"],
      "enable_completions": true,
      //Customise the quickview of you library, using python format syntax
    "quickview_format": "{citekey} - {title}",
    "auto_merge_citations": false
      }

**Comment by mangecoeur** [comment]
You should get tab-completion when you write a few characters of the citekey. check your bibfile path, restart sublimetext. If the problem persists try checking in the console for errors.

**Comment by mendelkranz** [comment]
I don't get any tab-completion. The citer plugin works when I invoke it through the search command, so the bibfile path can't be the problem. Restarting doesn't help, and I don't see anything in the console that would indicate any error of any sort. What should I do?
