### ISSUE TITLE
No fall back for bibtex_file_path or relative path?

### ISSUE THREAD

**Issue by katrinleinweber** [mangecoeur/Citer#24]
Hello and thank you for providing this useful helper :-)

Because I am working on two different computers, syncing my working directory, I tried setting the .bib file to:

    "bibtex_file_path": [
      "/Users/MAC/path/to/references.bib",
      "C:\\Users\\WIN7\\path\\to\\references.bib"
    ]

Of course, either one always triggers `FileNotFoundError` in `citer.py, lines:`
- `158, in on_api_ready    m.plugin_loaded()`
- `68, in plugin_loaded    refresh_caches()`
- `103, in refresh_caches    modified = modified or bibfile_modifed(single_path)` 
- `78, in bibfile_modifed    last_modified_time = os.path.getmtime(bib_path)`

Using only `"bibtex_file_path": "references.bib"` yields the same errors, except for `line 103` which becomes `line108, in refresh_caches    if bibfile_modifed(BIBFILE_PATH):`.

I can restrict myself to using Citer only on one of the computers, but is there a way to overcome the underlying problem? Maybe by implementing relative paths, or by reading out the project path from the `.sublime-project` file? Thanks for any advice!

**Comment by aammd** [comment]
This seems to work for me: adding the following to `project_name.sublime-project`:

````
	"settings":
	{
		"Citer":
		{
			"bibtex_file_path": "relative_path_from_project/biblio.bib",
		}
	}

````

**Comment by mangecoeur** [comment]
You can use a path relative to your project. Now, thanks to @bluebirch PR, you can also use environment variables (anything that is accepted by python `expandvar()` function)
