### ISSUE TITLE
Set ignore_nonstandard_types = False on BibtexParser object

### ISSUE THREAD

**Issue by bluebirch** [mangecoeur/Citer#26]
By default, bibtexparser ignores nonstandard types, which unfortunately means that many `biblatex` standard types are ignored as well. In order to include those as well, one can set `ignore_nonstandard_types = False`. This is not documented at https://bibtexparser.readthedocs.org/, but can be easily discerned from the source code.

**Comment by mangecoeur** [comment]
I would welcome a PR for this.

**Comment by bluebirch** [comment]
Working on it, but got caught in other stuff, such as a phd thesis. :-)

**Comment by bluebirch** [comment]
Fixed in pull request #31.
