### ISSUE TITLE
Request: Possibility to exclude scopes

### ISSUE THREAD

**Issue by openmedi** [mangecoeur/Citer#29]
The title says it all. It would be good to have the possibility to exclude (as opposed to the inclusive setting which already exists) specific scopes. This opens up the possibility to omit citer completions from showing up in specific parts of a file that will never be filled with citations.

An example: I am using [ikiwiki](https://ikiwiki.info/) and am developing a plugin with autocompletion for the tag directive, which looks like this:

```
[!tag  mytag othertag thirdtag]]
```

I developed a small syntax file which offers a a scope selector (`ikiwiki.derictives.tag`) for this specific part of a file, which in turn allows me to develop a completion file, that works in this scope selector. This works, but the citer plugin interferes, because it includes its completions in literally every part of the file. I would like to be able to exclude `ikiwiki.derictives.tag` from the scope citer includes its completions.

**Comment by mangecoeur** [comment]
I've added an option `excluded_scopes` in the latest version. If you could install the latest version from master and test it then I can make a release with the feature.

**Comment by openmedi** [comment]
Seems to be working for me. Thanks!

**Comment by mangecoeur** [comment]
Great. Got another PR pending , once that's done will make an official release

**Comment by mangecoeur** [comment]
Made a new release which should find its way into package control soonish

**Comment by choc96208** [comment]
Can you please add this `excluded_scopes` option to the documentation so more people know about it?

**Comment by mangecoeur** [comment]
@choc96208 done
