### ISSUE TITLE
Using BibTeX path in Windows

### ISSUE THREAD

**Issue by khalid-hussain** [mangecoeur/Citer#33]
Hi there,

I would like to use this plugin but I can't seem to get the path to the BibTeX file right.

I've tried:

```js
{
  "bibtex_file_path": "/d/Google Drive/University/Semester 3/INFO 6270 - Advanced HCI/project_lit_review/workspace/ahci_ref.bib",
}
```

I've also tried escaping the spaces:
```js
"/d/Google\\ Drive/University/Semester\\ 3/INFO\\ 6270\\ -\\ Advanced\\ HCI/project_lit_review/workspace/ahci_ref.bib"
```

I've also tried moving the `.bib` file to the root of `D:/`:
```js
{
  "bibtex_file_path": "/d/ahci_ref.bib"
}
```

The path is fine if I use Git bash, I'm able to `cat` the bib file. Any ideas?

**Comment by mangecoeur** [comment]
On windows I think you need to use the Windows style path format for it to be recognised, including the drive letter:

"D:\Google Drive\University\Semester 3/INFO 6270 - Advanced HCI\project_lit_review\workspace\ahci_ref.bib"

Some command line tools accept unix-style paths in Windows but I'm fairly sure python requires you to use Windows style ones in this case.

**Comment by mangecoeur** [comment]
Closing for now
