### ISSUE TITLE
Performance for large bibtex files

### ISSUE THREAD

**Issue by reagle** [mangecoeur/Citer#5]
It might be unrealistic to expect anything else, but Citer causes a six second lock at ST3 startup while it processes my 2.1MB bibtex file. Some ideas:
1. Can citer be non-blocking?
2.  Depending on where the slow-down is, maybe it could cache/serialize its data-structure.
3. Faster parser? I fear this is improbable as I've never been happy with any pure-python parsers, other than the [stripped down ones](https://github.com/reagle/pandoc-wrappers/blob/master/md2bib.py) I use for a constrained type of bibtex. That said, you don't really need a fancy parser.

As an aside, I note the dependency expects old-school bibtex (where @online type is not permitted) rather than biblatex. In any case, I'm moving away from that towards CSL YAML, which is where pandoc is headed.

**Comment by mangecoeur** [comment]
Closing as inactive
