### ISSUE TITLE
Handle more than one BibTeX file [feature request]

### ISSUE THREAD

**Issue by bluebirch** [mangecoeur/Citer#6]
Current implementation allows for one BibTeX file only, whereas I have my (pretty large) bibliography split into three files.

I do realize this is more of a feature request than a bug report.

**Comment by aaronwolen** [comment]
+1 for supporting project specific BibTeX files.

**Comment by cuttlefishh** [comment]
Another +1 for supporting multiple BibTeX files. I also use a separate .bib file for each paper. Generating one single .bib file is much slower, and that has to be done each time I add a paper to my library (Papers2). Thanks!

**Comment by mangecoeur** [comment]
This has been added by @nicholasbloom , but I haven't had the time to check everything before making a new release.

**Comment by mangecoeur** [comment]
This has been added to the latest release

**Comment by orschiro** [comment]
@mangecoeur 

Fantastic, thanks for implementing!

Robert
