### ISSUE TITLE
Citer not finding bibtex file

### ISSUE THREAD

**Issue by cddesja** [mangecoeur/Citer#7]
Citer is unable to find my bibtex file. I have set in Preferences.sublime-settings in the User Settings:

     "bibtex_file_path": "Users/chris/Dropbox/literature/literature.bib",

But when Sublime 3 launches I get "WARNING: No bitex file configured for Citer.

This is on a Mac 10.9. It's unclear to me what the issue is. I have tried putting the bib in a file different locations.  

Also, the warning message bitex should be either bibtex or BibTeX in citer.py.

**Comment by christinamccabe** [comment]
Hello, I'm having the same issues here. 
When searching for a cite key, I receive the message: "Warning: No bobtex file configured for Citer".
I've followed the advice above (deleted user settings file, restarted, recreated; checked capitalisation of commands), as well as trying to save my bib file in different locations. 
Just can't work it out, and would be very grateful for any advice. 

Configuration code:
{
    //REQUIRED:

    "bibtex_file_path": "/Users/cmc/Library/Mobile Documents/com~apple~CloudDocs/folder/20220901.bib",
    // You can also specify a list
    //"bibtex_file_path": ["example/path/to/file.bib", "example/path/to/fileTwo.bib"],

    //OPTIONAL:

    //By default Citer Search looks for your keyword in the 
    //author, title, year, and Citekey (id) fields
    "search_fields": ["author", "title", "year", "id"] ,
    //Default format is @Citekey
    "citation_format": "@%s",
    //list of scopes. Could be top level "text" or "source", or limit to
    // e.g "text.html.markdown"
    "completions_scopes": ["text"],
    "enable_completions": true,
    //Customise the quickview of you library, using python format syntax
    "quickview_format": "{citekey} - {title}",
    "auto_merge_citations": true
}
